MAP = {
    'Vattene': 'Go away',
    'Viene qui': 'Come here',
    'Perfetto': 'Perfect',
    'E un furbo': 'Crafty',
    'Che due palle': 'No fun',
    'Che vuoi': 'What do you want',
    'Vanno d’accordo': 'They get together',
    'Sei pazzo': 'Are you crazy?',
    'Cos hai combinato': 'What have you donw?',
    'Nonme me frega niente': 'There is no interest to me',
    'Ok': 'Ok',
    'Cosa ti farei': 'What whould you do?',
    'Basta': 'Enough already',
    'Le vuoi prendere': 'You want to take',
    'Non ce ne piu': 'No good any more',
    'Ho fame': 'I’m hungry',
    'Tanto tempo fa': 'That was a long time ago',
    'Buonissimo': 'It’s very delicious',
    'Si sono messi d’accordo': 'They have agreed',
    'Sono stufo': 'I’m sick and tired of it',
}